In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.models import Sequential
from keras.layers.core import Dense, Dropout

In [2]:
#Create a sequential model and add a layer with relu activation
model = Sequential()
model.add(layers.Dense(2, activation="relu"))

In [3]:
#We've added one layer
print(len(model.layers))

1


In [4]:
#the model doesn't have any inputs yet, so there are no weights and this throws an error.
model.weights

ValueError: Weights for model sequential have not yet been created. Weights are created when the Model is first called on inputs or `build()` is called with an `input_shape`.

In [5]:
#give a simple input to the model
x=tf.ones((1,4))
y=model(x)

In [6]:
#Now there are model weights!
model.weights

[<tf.Variable 'dense/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.85365653,  0.380944  ],
        [ 0.9024508 , -0.8011701 ],
        [-0.91988087,  0.05147123],
        [-0.7158685 ,  0.9899423 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [7]:
#and you can see the summary of the model. There is one layer with the output shape of "2" that we entered above
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (1, 2)                    10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [8]:
#Make a new model and this time start with an input shape
model = Sequential()
model.add(layers.Dense(2, activation="relu", input_shape=(4,)))
model.add(layers.Dense(3))
model.add(layers.Dense(4))

In [9]:
#this model also has more layers
print(len(model.layers))

3


In [10]:
#model weights are there even though the model hasn't been run yet
model.weights

[<tf.Variable 'dense_1/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.47912264, -0.15604377],
        [ 0.8469124 , -0.82416487],
        [ 0.16247296, -0.6800709 ],
        [-0.22439599, -0.86719847]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[-0.39560097, -0.3109063 ,  0.9804952 ],
        [-0.83248997,  0.6096231 ,  0.958935  ]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_3/kernel:0' shape=(3, 4) dtype=float32, numpy=
 array([[-0.5270744 , -0.79716694,  0.12570179, -0.6041929 ],
        [-0.4451168 ,  0.41374207, -0.021357  ,  0.6581949 ],
        [ 0.3749944 , -0.7664725 ,  0.5407655 ,  0.4218253 ]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [11]:
#Now the model shows three layers, each of the type entered above, but there are no inputs yet.
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
 dense_2 (Dense)             (None, 3)                 9         
                                                                 
 dense_3 (Dense)             (None, 4)                 16        
                                                                 
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________
